import { Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "download.sh",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" color-scheme="light">
      <body className={`${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
